AllCops:
  Enabled: true
  Exclude:
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/bin/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'spec/support/factory_girl.rb'
    - 'app/models/**/*'
    - 'app/helpers/**/*'
    - 'Gemfile'
    - 'config.ru'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 120

Metrics/AbcSize:
  Max: 90